### PR TITLE
Validate station on post

### PR DESCRIPTION
**Pull request by juliusmarminge**
This PR implements the requested functionality that every request should be validated in terms of what station is sending it. Now, Every POST-request have to specify the stationId, and all the sensors used in the request has to be linked to that sensor in order for the request to be accepted.

Given
```js
stations = [
  { stationId: 1, sensorIds: [ 1, 2 ], locationId: 1 },
  { stationId: 2, sensorIds: [ 3, 4 ], locationId: 2 }
]
```
A valid request would now look like
```json
{
  "time": "2022-05-09T10:59:12",
  "stationId": 1,
  "position": {
    "lat": 10.23421341,
    "long": 25.345324214
  },
  "sensors": [
    {
      "id": 1,
      "value": 20,
      "unit": "c"
    },
    {
      "id": 2,
      "value": 25000,
      "unit": "ppm"
    }
  ]
}
```
whereas the same request but specifying sensorIds 3 and 4 would be invalid.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
@andreas-bauer we got this information from the sensor-group. is this what you meant?

**Comment by andreas-bauer** [comment]
It is important that stations can be identified to debug the hardware. I'm not sure how strict the API should be. 

I saw your comment `// TODO: should we automatically create the station?`. It would be good if a station is created if the `ID` doesn't exist. This would simplify the setup process since the debugging capabilities on the hardware side are limited.

**Comment by juliusmarminge** [comment]
> It is important that stations can be identified to debug the hardware. I'm not sure how strict the API should be.
> 
> I saw your comment `// TODO: should we automatically create the station?`. It would be good if a station is created if the `ID` doesn't exist. This would simplify the setup process since the debugging capabilities on the hardware side are limited.

Ok. Should it then check if any of the sensors are already linked to another station before creating the station? E.g. in the example JSON above, if I specify `stationId: 3`, should it then create station 3 with sensors 1 and 2 even though they are linked to station 1?

**Comment by andreas-bauer** [comment]
Creating a new sensor with id for each station even if it is the same type of hardware is unecessary complicated. 
Does it cause any DB issues when you use the same sensor id, which represents the same type of hardware sensor, in multiple stations?

**Comment by juliusmarminge** [comment]
> Does it cause any DB issues when you use the same sensor id, which represents the same type of hardware sensor, in multiple stations?

It wouldn't, no. The uniqueness of `id`<->`physical sensor` is however needed to keep track of that particular sensor's status. If you should use the same sensorId for multiple physical sensors this functionality would need to be overhauled.

**Comment by juliusmarminge** [comment]
image
this is what happens when sensors that are linked to another station sends measurements with a different stationId

**Comment by juliusmarminge** [comment]
@andreas-bauer is this solution fine for now? you can change it later but in order to keep the sensor statuses accurate this "stricter" contract would make sense for now

**Pull request merged**
